### ISSUE TITLE
Error during yaml to json conversion

### ISSUE THREAD

**Issue by chummar** [wakeful/yaml2json#1]
command issued : 
cat 211028.yaml | yaml2json

Error : 
panic: interface conversion: interface {} is float64, not string

goroutine 1 [running]:
main.decode(0x5192c0, 0xc4200768a0, 0xffffffffffffffff, 0x0)
	/home/travis/gopath/src/github.com/wakeful/yaml2json/decode.go:8 +0x359
main.decode(0x50d8e0, 0xc42019e100, 0xc4200125fc, 0x4)
	/home/travis/gopath/src/github.com/wakeful/yaml2json/decode.go:13 +0xd1
main.decode(0x5192c0, 0xc420076870, 0xc420043c98, 0x0)
	/home/travis/gopath/src/github.com/wakeful/yaml2json/decode.go:8 +0x248
main.decode(0x5192c0, 0xc4200767e0, 0xffffffffffffffff, 0x0)
	/home/travis/gopath/src/github.com/wakeful/yaml2json/decode.go:8 +0x248
main.decode(0x50d8e0, 0xc42019e640, 0xc420043e58, 0x0)
	/home/travis/gopath/src/github.com/wakeful/yaml2json/decode.go:13 +0xd1
main.decode(0x5192c0, 0xc4200765a0, 0xfe00, 0x509160)
	/home/travis/gopath/src/github.com/wakeful/yaml2json/decode.go:8 +0x248
main.main()
	/home/travis/gopath/src/github.com/wakeful/yaml2json/yaml2json.go:24 +0x18d

**Comment by wakeful** [comment]
thanks for reporting the issue, can you also share the file you are trying to convert?

**Comment by mattdeboard** [comment]
I am experiencing this issue as well but unfortunately I can't share the file as it's corporate. The error I get is the same except it's `interface {} is int, not string`.

Is it possible to spit out line number on panic?

**Comment by wakeful** [comment]
@chummar and @mattdeboard  can you check against [v0.3.1](https://github.com/wakeful/yaml2json/releases/tag/0.3.1)  stack trace is suggesting that we have an `int` / `float` type key on the left side
