### ISSUE TITLE
Brew install doesn't work any more

### ISSUE THREAD

**Issue by coandco** [wakeful/yaml2json#2]
colson@MBP-colson:~$ brew tap wakeful/selection
    Updating Homebrew...
    ==> Tapping wakeful/selection
    Cloning into '/usr/local/Homebrew/Library/Taps/wakeful/homebrew-selection'...
    remote: Enumerating objects: 8, done.
    remote: Counting objects: 100% (8/8), done.
    remote: Compressing objects: 100% (8/8), done.
    remote: Total 8 (delta 0), reused 5 (delta 0), pack-reused 0
    Unpacking objects: 100% (8/8), done.
    Tapped 3 formulae (36 files, 28.5KB).
    colson@MBP-colson:~$ brew install yaml2json
    ==> Installing yaml2json from wakeful/selection
    ==> Downloading https://github.com/wakeful/yaml2json/releases/download/0.3.1/yaml2json-darwin-amd64
    ==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/83977943/25e63980-d11a-11e8-9e2a-a67f08ab855d?X-Amz-Algorithm=AW
    ######################################################################## 100.0%
    Error: An exception occurred within a child process:
      ChecksumMismatchError: SHA256 mismatch
    Expected: 54dac603087827033e74f9396e220e70a463a5949bfc36ce0e2c445ab41845cb
    Actual: 466763d034da7014c8cb4b8208ef0cf750a76a90974f8ddaa717023e413ffa51
    Archive: /Users/colson/Library/Caches/Homebrew/downloads/f7dd8de39cb737aee27d42fcfc1c2888c615a2b9adf6831a7264ed6fbd4d6db2--yaml2json-darwin-amd64
    To retry an incomplete download, remove the file above.

There's currently an SHA mismatch when trying to install yaml2json with Homebrew.

**Comment by wakeful** [comment]
I have resolve the issue, please refresh `tap` by running  `brew update`.
thanks for reporting!
