### ISSUE TITLE
ChecksumMismatchError: SHA256 mismatch

### ISSUE THREAD

**Issue by gmsaladin** [wakeful/yaml2json#3]
There is currrently a SHA mismatch

==> Downloading https://gitlab.com/inkscape/inkscape/commit/93ccf03162cd2e46d962822d5507865f3451168c
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 1f037cc29cee8e0c60ab4753d4151741c8170e4849129bac68fdc60925eb971d
Actual: 7ce4f70f1cb03cd0bab7dc94821a89bf71600bd59c763ae0d78c48f33db3d9ac
Archive: /Users/gmuhammadsalahuddin/Library/Caches/Homebrew/downloads/369b021412bac03164fd51cdf072f9e402caea5fabf430466d2d9779d6208a36--93ccf03162cd2e46d962822d5507865f3451168c.diff
To retry an incomplete download, remove the file above.

**Comment by wakeful** [comment]
this issue is related to [inkscape](https://inkscape.org/) software and [Homebrew](https://brew.sh/) formulas - closing.
