### ISSUE TITLE
`-version` exits 2

### ISSUE THREAD

**Issue by DanielJonesEB** [wakeful/yaml2json#4]
Hi, thanks for the tool. I'm trying to bake it into a Docker image as part of a CI job, and we run `--version` against all binaries we install`. Despite `yaml2json` expecting `-version` with a single dash, it still gives the expected output.

The problem is that it exits with 2 regardless of whether you use `-version` or `--version`, which is causing our verification script to fail. I'd expect it to exit 0 as there hasn't been an error.

**Comment by wakeful** [comment]
@DanielJonesEB  thanks for the suggestion I have corrected the exit code, please try with new [version](https://github.com/wakeful/yaml2json/releases/tag/0.4.0).

**Comment by DanielJonesEB** [comment]
Yep, that works now. Thanks for the prompt response!
